# Generated by Django 5.1.3 on 2025-01-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='color',
            field=models.CharField(default='hsl(202, 70%, 85%)', max_length=150),
        ),
    ]
