# Generated by Django 5.1.3 on 2024-11-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='color',
            field=models.CharField(default='hsl(92%, 70%, 84%)', max_length=150),
        ),
    ]
