# Generated by Django 5.1.3 on 2025-02-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='color',
        ),
    ]
