# Generated by Django 5.1.3 on 2024-11-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_db', '0002_alter_contact_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='color',
            field=models.CharField(default='hsl(202, 70%, 85%)', max_length=150),
        ),
    ]
